export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';

export const FETCH_TASK_OPTIONS_START = 'FETCH_TASK_OPTIONS_START';
export const FETCH_TASK_OPTIONS_SUCCESS = 'FETCH_TASK_OPTIONS_SUCCESS';
export const FETCH_TASK_OPTIONS_FAIL = 'FETCH_TASK_OPTIONS_FAIL';