export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';

export const FETCH_TASK_OPTIONS_START = 'FETCH_TASK_OPTIONS_START';
export const FETCH_TASK_OPTIONS_SUCCESS = 'FETCH_TASK_OPTIONS_SUCCESS';
export const FETCH_TASK_OPTIONS_FAIL = 'FETCH_TASK_OPTIONS_FAIL';

export const FETCH_RESOURCE_SCHEDULE_START = 'FETCH_RESOURCE_SCHEDULE_START'
export const FETCH_RESOURCE_SCHEDULE_SUCCESS = 'FETCH_RESOURCE_SCHEDULE_SUCCESS'
export const FETCH_RESOURCE_SCHEDULE_FAIL = 'FETCH_RESOURCE_SCHEDULE_FAIL'

export const HANDLE_SCHEDULE_PLACEMENT = 'HANDLE_SCHEDULE_PLACEMENT'

export const SHOW_TASK_DETAILS = 'SHOW_TASK_DETAILS'
export const HIDE_TASK_DETAILS = 'HIDE_TASK_DETAILS'

export const TOGGLE_TASK_NEW = 'TOGGLE_TASK_NEW'

export const FETCH_CLIENT_RESOURCES_START = 'FETCH_CLIENT_RESOURCES_START'
export const FETCH_CLIENT_RESOURCES_SUCCESS = 'FETCH_CLIENT_RESOURCES_SUCCESS'
export const FETCH_CLIENT_RESOURCES_FAIL = 'FETCH_CLIENT_RESOURCES_FAIL'

export const FETCH_UNSCHEDULED_TASKS_START = 'FETCH_UNSCHEDULED_TASKS_START'
export const FETCH_UNSCHEDULED_TASKS_SUCCESS = 'FETCH_UNSCHEDULED_TASKS_SUCCESS'
export const FETCH_UNSCHEDULED_TASKS_FAIL = 'FETCH_UNSCHEDULED_TASKS_FAIL'