export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';

export const FETCH_TASK_OPTIONS_START = 'FETCH_TASK_OPTIONS_START';
export const FETCH_TASK_OPTIONS_SUCCESS = 'FETCH_TASK_OPTIONS_SUCCESS';
export const FETCH_TASK_OPTIONS_FAIL = 'FETCH_TASK_OPTIONS_FAIL';

export const FETCH_RESOURCE_SCHEDULE_START = 'FETCH_RESOURCE_SCHEDULE_START'
export const FETCH_RESOURCE_SCHEDULE_SUCCESS = 'FETCH_RESOURCE_SCHEDULE_SUCCESS'
export const FETCH_RESOURCE_SCHEDULE_FAIL = 'FETCH_RESOURCE_SCHEDULE_FAIL'

export const HANDLE_SCHEDULE_PLACEMENT = 'HANDLE_SCHEDULE_PLACEMENT'

export const SHOW_TASK_DETAILS = 'SHOW_TASK_DETAILS'
